### ISSUE TITLE
Migration from none to 0.2.0 to 0.3.0 doesn't work

### ISSUE THREAD

**Issue by AlexZeitler** [PDMLab/massive-migrate-semver#5]
```
mocha -g '0.2.0 to 0.3.0' test/test.js


  When running migration from existing pgmigration table from 0.2.0 to 0.3.0
up error while updating customer table:  { [Error: relation "public.customer" does not exist] message: 'relation "public.customer" does not exist' }
    1) should contain 4 tables


  0 passing (356ms)
  1 failing

  1) When running migration from existing pgmigration table from 0.2.0 to 0.3.0 should contain 4 tables:
     Uncaught Error: Callback was already called.
      at node_modules/async/lib/async.js:43:36
      at node_modules/async/lib/async.js:694:17
      at node_modules/async/lib/async.js:173:37
      at Object.next (test/migrations/none-0.2.0-0.3.0/0.2.0/0.2.0-up.js:11:17)
      at null.callback (node_modules/massive/lib/runner.js:53:16)
      at Query.handleError (node_modules/massive/node_modules/pg/lib/query.js:106:17)
      at null.<anonymous> (node_modules/massive/node_modules/pg/lib/client.js:171:26)
      at Socket.<anonymous> (node_modules/massive/node_modules/pg/lib/connection.js:109:12)
      at readableAddChunk (_stream_readable.js:163:16)
      at Socket.Readable.push (_stream_readable.js:126:10)
      at TCP.onread (net.js:538:20)
```

**Comment by AlexZeitler** [comment]
`0.1.0 -> 0.2.0 -> 0.3.0` also does not work.
